#!/usr/bin/env python3
"""Generate a project documentation site (Fumadocs MDX pages) from a project's .bimai/ folder.

Deterministic: no model involved, so the site always matches the project files.
Written for people who don't open VS Code: new colleagues, managers, directors and the
client's BIM manager.

Usage:
  generate_site.py <project_root> <content_out_dir> [--public-dir DIR] [--files-url URL]
                   [--base-url URL] [--today YYYY-MM-DD]

  project_root     folder that contains .bimai/
  content_out_dir  Fumadocs content folder for this project (overwritten)
  --public-dir     where to copy shareable project files such as the BEP (optional)
  --files-url      URL prefix under which --public-dir is served (default /project-files/<id>)
  --base-url       URL of the generated pages (default /docs)
  --today          reference date for "this week" (default: today)

Never included: raw transcripts, raw data exports, anyone's desk, private journal sessions,
secrets. Only files the project already shares with its whole team are read.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import shutil
import sys
from pathlib import Path

import yaml

# ---------------------------------------------------------------- role catalogue
# Mirrors the role charters in the bimai plugin (§5.1). The plugin's charters take
# precedence once they exist; this keeps the generator usable on its own.
ROLES = {
    "coordinator": ("🧭", "Coordinator", "sonnet", {"en": "Runs the team and the workflows, talks to the person", "nl": "Leidt het team en de werkstromen, praat met de persoon"}),
    "requirements-risk-manager": ("📐", "Requirements & Risk Manager", "sonnet", {"en": "Requirements, verification and risks", "nl": "Eisen, verificatie en risico's"}),
    "planning-analyst": ("📅", "Planning Analyst", "haiku", {"en": "Milestones, critical path, slipping deliverables", "nl": "Mijlpalen, kritiek pad, uitlopende leveringen"}),
    "information-manager": ("🗂️", "Information Manager", "sonnet", {"en": "BEP compliance, naming, deliveries", "nl": "BUP-naleving, naamgeving, leveringen"}),
    "model-checker": ("🔍", "Model Checker", "haiku", {"en": "Checks models against the agreements", "nl": "Toetst modellen aan de afspraken"}),
    "issue-manager": ("📋", "Issue Manager", "haiku", {"en": "Triages and follows up issues", "nl": "Triageert en bewaakt issues"}),
    "scribe": ("✍️", "Scribe", "sonnet", {"en": "Minutes, reports, decision log", "nl": "Notulen, rapportages, besluitenlijst"}),
    "mentor": ("🎓", "Mentor", "haiku", {"en": "Explains the tools, on request", "nl": "Legt de tools uit, op verzoek"}),
    "builder": ("🛠️", "Builder", "sonnet", {"en": "Adds new tools to bimai", "nl": "Voegt nieuwe tools toe aan bimai"}),
}

# ---------------------------------------------------------------- strings (en / nl)
STRINGS = {
    "en": {
        "overview": "Overview", "people": "People", "ai_teams": "AI teams", "how_we_work": "How we work",
        "agreements": "Agreements", "decisions": "Decisions", "meetings": "Meetings", "this_week": "This week",
        "demo_note": "This is a fictional demo project. All people, organizations and data are made up.",
        "generated_note": "Generated by bimai from the project files on {date}. Don't edit this site; change the project instead.",
        "goal": "Goal", "phase": "Phase", "contract": "Contract", "client": "Client",
        "at_a_glance": "At a glance", "people_n": "people on the project", "positions_n": "positions",
        "agents_n": "AI agents across all teams", "decisions_n": "decisions", "meetings_n": "meetings processed",
        "open_tasks_n": "open tasks", "open_handoffs_n": "open handoffs",
        "next_milestones": "Next milestones", "milestone": "Milestone", "date": "Date", "links": "Links",
        "bep_card": "BIM execution plan", "bep_card_desc": "The agreements this project works by",
        "positions": "Positions", "position": "Position", "role": "Role", "scope": "Scope", "held_by": "Held by",
        "lead": "lead", "cover": "Cover", "covers": "covers {pos} until {until}",
        "responsibilities": "Responsibilities", "external": "External parties", "organization": "Organization",
        "name": "Name", "title": "Title", "who_owns_what": "Who owns what", "responsibility": "Responsibility",
        "people_intro": "A **position** is a job on the project. People hold positions; what the AI agents learn in a job stays with the position, so whoever takes over starts with everything.",
        "teams_intro": "Every person has their own small AI team, chosen for their role and the data they work with. The teams share the project's agreements and decisions, and hand work to each other instead of doing it twice.",
        "member": "Member", "why": "Why", "model": "Model", "what_it_does": "What it does",
        "handoffs_title": "How the teams hand work to each other", "handoff": "Handoff", "from": "From", "to": "To", "status": "Status",
        "no_handoffs": "No handoffs yet.",
        "approvals": "Approvals", "write_mode": "Changes to models and ACC",
        "write_mode_read-only": "Read-only: agents don't change anything.",
        "write_mode_gated-write": "Agents propose changes; a person approves each one first.",
        "rule_owners": "Changes to shared rules are approved by", "rhythm": "Coordination rhythm",
        "workflows": "Workflows", "automations": "Automations", "schedule": "Schedule", "owner": "Owner", "mode": "Mode",
        "flow_intro": "How a request flows through a team:",
        "documents": "Documents", "download": "Download", "software": "Software and versions", "app": "App", "version": "Version",
        "used_for": "Used for", "source": "Source", "cde": "CDE and status codes", "naming": "Naming", "coordinates": "Coordinates",
        "exchange": "Exchange formats", "classification": "Classification", "milestones": "Milestones",
        "open_questions": "Open questions", "other_agreements": "Other agreements",
        "agreements_intro": "Read from the BIM execution plan and confirmed by the project team. Every agreement shows the page it came from.",
        "decision_by": "Decided {date} · recorded by {by}", "replaces": "Replaces", "deviates": "Deviates from",
        "meetings_intro": "Minutes of every processed meeting. Every line links back to its timestamp in the transcript.",
        "uploaded_by": "Processed by {by}", "participants": "Participants",
        "journal": "What the teams did", "private_session": "A private session (not shared).",
        "due_soon": "Due in the next 14 days", "task": "Task", "due": "Due", "recent_decisions": "Recent decisions",
        "nothing_yet": "Nothing yet.", "open": "open", "done": "done", "weekdays": "Weekdays", "every": "Every",
    },
    "nl": {
        "overview": "Overzicht", "people": "Mensen", "ai_teams": "AI-teams", "how_we_work": "Zo werken we",
        "agreements": "Afspraken", "decisions": "Besluiten", "meetings": "Overleggen", "this_week": "Deze week",
        "demo_note": "Dit is een fictief demoproject. Alle mensen, organisaties en gegevens zijn verzonnen.",
        "generated_note": "Gegenereerd door bimai uit de projectbestanden op {date}. Pas deze site niet aan; pas het project aan.",
        "goal": "Doel", "phase": "Fase", "contract": "Contract", "client": "Opdrachtgever",
        "at_a_glance": "In één oogopslag", "people_n": "mensen op het project", "positions_n": "posities",
        "agents_n": "AI-agents in alle teams", "decisions_n": "besluiten", "meetings_n": "verwerkte overleggen",
        "open_tasks_n": "open taken", "open_handoffs_n": "open overdrachten",
        "next_milestones": "Volgende mijlpalen", "milestone": "Mijlpaal", "date": "Datum", "links": "Links",
        "bep_card": "BIM-uitvoeringsplan", "bep_card_desc": "De afspraken waar dit project mee werkt",
        "positions": "Posities", "position": "Positie", "role": "Rol", "scope": "Scope", "held_by": "Bezet door",
        "lead": "lead", "cover": "Vervanging", "covers": "vervangt {pos} tot {until}",
        "responsibilities": "Verantwoordelijkheden", "external": "Externe partijen", "organization": "Organisatie",
        "name": "Naam", "title": "Functie", "who_owns_what": "Wie is waarvan eigenaar", "responsibility": "Verantwoordelijkheid",
        "people_intro": "Een **positie** is een functie op het project. Mensen bezetten posities; wat de AI-agents in een functie leren blijft bij de positie, zodat een opvolger met alles begint.",
        "teams_intro": "Iedereen heeft een eigen klein AI-team, gekozen voor zijn rol en de gegevens waarmee hij werkt. De teams delen de afspraken en besluiten van het project en dragen werk aan elkaar over in plaats van het dubbel te doen.",
        "member": "Lid", "why": "Waarom", "model": "Model", "what_it_does": "Wat het doet",
        "handoffs_title": "Hoe de teams werk aan elkaar overdragen", "handoff": "Overdracht", "from": "Van", "to": "Naar", "status": "Status",
        "no_handoffs": "Nog geen overdrachten.",
        "approvals": "Goedkeuringen", "write_mode": "Wijzigingen in modellen en ACC",
        "write_mode_read-only": "Alleen lezen: agents wijzigen niets.",
        "write_mode_gated-write": "Agents stellen wijzigingen voor; een persoon keurt elke wijziging eerst goed.",
        "rule_owners": "Wijzigingen in gedeelde afspraken worden goedgekeurd door", "rhythm": "Overlegritme",
        "workflows": "Werkstromen", "automations": "Automatiseringen", "schedule": "Planning", "owner": "Eigenaar", "mode": "Modus",
        "flow_intro": "Zo loopt een verzoek door een team:",
        "documents": "Documenten", "download": "Download", "software": "Software en versies", "app": "Applicatie", "version": "Versie",
        "used_for": "Gebruikt voor", "source": "Bron", "cde": "CDE en statuscodes", "naming": "Naamgeving", "coordinates": "Coördinaten",
        "exchange": "Uitwisselformaten", "classification": "Classificatie", "milestones": "Mijlpalen",
        "open_questions": "Open vragen", "other_agreements": "Overige afspraken",
        "agreements_intro": "Gelezen uit het BIM-uitvoeringsplan en bevestigd door het projectteam. Bij elke afspraak staat de pagina waar hij vandaan komt.",
        "decision_by": "Besloten {date} · vastgelegd door {by}", "replaces": "Vervangt", "deviates": "Wijkt af van",
        "meetings_intro": "Notulen van elk verwerkt overleg. Elke regel verwijst naar het tijdstip in het transcript.",
        "uploaded_by": "Verwerkt door {by}", "participants": "Deelnemers",
        "journal": "Wat de teams deden", "private_session": "Een privésessie (niet gedeeld).",
        "due_soon": "Deadline in de komende 14 dagen", "task": "Taak", "due": "Deadline", "recent_decisions": "Recente besluiten",
        "nothing_yet": "Nog niets.", "open": "open", "done": "klaar", "weekdays": "Werkdagen", "every": "Elke",
    },
}
WEEKDAYS = {"en": ["Sundays", "Mondays", "Tuesdays", "Wednesdays", "Thursdays", "Fridays", "Saturdays"],
            "nl": ["zondag", "maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag"]}


# ---------------------------------------------------------------- escaping
_MDX_SPECIAL = str.maketrans({"{": "\\{", "}": "\\}", "<": "&lt;", ">": "&gt;"})


def mdx_text(value) -> str:
    """Escape free text for MDX (no JSX, no expressions)."""
    return "" if value is None else str(value).translate(_MDX_SPECIAL)


def mdx_cell(value) -> str:
    """Escape text for a Markdown table cell."""
    return mdx_text(value).replace("|", "\\|").replace("\n", " ").strip() or "—"


def mdx_markdown(markdown: str) -> str:
    """Make a Markdown document safe to embed in MDX, keeping code blocks and inline code intact."""
    out, in_fence = [], False
    for line in markdown.splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            out.append(line)
            continue
        if in_fence:
            out.append(line)
            continue
        parts = line.split("`")
        # even-indexed parts are outside inline code
        out.append("`".join(mdx_text(p) if i % 2 == 0 else p for i, p in enumerate(parts)))
    return "\n".join(out)


def mm(value) -> str:
    """Escape text for a quoted Mermaid label."""
    return re.sub(r"[<>{}\[\]]", "", str(value)).replace('"', "#quot;")


def short(value: str, limit: int = 48) -> str:
    """Shorten on a word boundary, for diagram labels."""
    value = str(value)
    if len(value) <= limit:
        return value
    return value[:limit].rsplit(" ", 1)[0].rstrip(",.;:") + "…"


def node_id(prefix: str, value: str) -> str:
    return prefix + re.sub(r"\W", "_", value)


# ---------------------------------------------------------------- loading
def _yaml(path: Path, default=None):
    if not path.exists():
        return default
    return yaml.safe_load(path.read_text(encoding="utf-8")) or default


def _front_matter(path: Path) -> tuple[dict, str]:
    text = path.read_text(encoding="utf-8")
    if text.startswith("---"):
        _, fm, body = text.split("---", 2)
        return yaml.safe_load(fm) or {}, body.strip()
    return {}, text.strip()


def load_project(root: Path) -> dict:
    b = root / ".bimai"
    if not (b / "project.yaml").exists():
        raise FileNotFoundError(f"No .bimai/project.yaml under {root}")
    seats = {}
    for seat_dir in sorted((b / "seats").glob("*/")):
        seat = _yaml(seat_dir / "seat.yaml", {}) or {}
        seat["id"] = seat_dir.name
        seat["tasks"] = _yaml(seat_dir / "tasks.yaml", []) or []
        seat["journal"] = [dict(_front_matter(p)[0], body=_front_matter(p)[1], file=p.name)
                           for p in sorted((seat_dir / "journal").glob("*.md"))]
        seats[seat_dir.name] = seat
    decisions = [dict(fm, body=body) for fm, body in (_front_matter(p) for p in sorted((b / "decisions").glob("*.md")))]
    meetings = []
    for m_dir in sorted((b / "meetings").glob("*/")):
        meta = _yaml(m_dir / "meeting.yaml", {}) or {}
        if meta.get("status") != "applied" or not (m_dir / "minutes.md").exists():
            continue  # pending meetings are not shown until the uploader has confirmed them
        meta["slug"] = m_dir.name
        meta["minutes"] = (m_dir / "minutes.md").read_text(encoding="utf-8")
        meetings.append(meta)
    handoffs = []
    for p in sorted((b / "positions").glob("*/handoffs/*.yaml")):
        handoffs.append(_yaml(p, {}))
    workflows = [_yaml(p, {}) for p in sorted((b / "workflows").glob("*.yaml"))]
    automations = [_yaml(p, {}) for p in sorted((b / "automations").glob("*.yaml"))]
    return {
        "root": root,
        "project": _yaml(b / "project.yaml", {}),
        "agreements": _yaml(b / "agreements.yaml", {}) or {},
        "people": (_yaml(b / "people.yaml", {}) or {}).get("people", []),
        "ownership": _yaml(b / "ownership.yaml", {}) or {},
        "seats": seats,
        "decisions": sorted(decisions, key=lambda d: str(d.get("date", "")), reverse=True),
        "meetings": sorted(meetings, key=lambda m: str(m.get("date", "")), reverse=True),
        "handoffs": sorted(handoffs, key=lambda h: str(h.get("date", "")), reverse=True),
        "workflows": workflows,
        "automations": automations,
    }


# ---------------------------------------------------------------- helpers
class Site:
    def __init__(self, data: dict, base_url: str, files_url: str, today: dt.date):
        self.d = data
        self.p = data["project"]
        self.lang = self.p.get("language", "en") if self.p.get("language") in STRINGS else "en"
        self.base = base_url.rstrip("/")
        self.files_url = files_url.rstrip("/")
        self.today = today
        self.people = {p["id"]: p for p in data["people"]}
        self.by_seat = {p.get("seat"): p for p in data["people"] if p.get("seat")}
        self.positions = data["ownership"].get("positions", {}) or {}
        self.cover = data["ownership"].get("cover", []) or []
        self.docs = {d["id"]: d for d in data["agreements"].get("source_documents", []) or []}

    def t(self, key: str, **kw) -> str:
        return STRINGS[self.lang][key].format(**kw)

    def url(self, page: str = "") -> str:
        return f"{self.base}/{page}".rstrip("/")

    def seat_name(self, seat: str) -> str:
        return self.by_seat.get(seat, {}).get("name", seat)

    def person_name(self, pid: str) -> str:
        return self.people.get(pid, {}).get("name") or self.seat_name(pid)

    def source(self, src: dict | None) -> str:
        if not src:
            return "—"
        doc = self.docs.get(src.get("doc"), {})
        title = doc.get("title", src.get("doc", ""))
        parts = [title]
        if src.get("page"):
            parts.append(f"p. {src['page']}")
        if src.get("section"):
            parts.append(f"§{src['section']}")
        return mdx_cell(" · ".join(str(p) for p in parts if p))

    def active_cover(self) -> list[dict]:
        out = []
        for c in self.cover:
            until = dt.date.fromisoformat(str(c["until"]))
            start = dt.date.fromisoformat(str(c.get("from", c["until"])))
            if until >= self.today and start <= self.today + dt.timedelta(days=14):
                out.append(c)
        return out

    def cron_human(self, cron: str) -> str:
        parts = str(cron).split()
        if len(parts) != 5:
            return mdx_text(cron)
        minute, hour, dom, month, dow = parts
        if not (minute.isdigit() and hour.isdigit() and dom == "*" and month == "*"):
            return f"`{cron}`"
        at = f"{int(hour):02d}:{int(minute):02d}"
        if dow == "1-5":
            return f"{self.t('weekdays')} {at}"
        if dow.isdigit():
            day = WEEKDAYS[self.lang][int(dow) % 7]
            return f"{day[0].upper() + day[1:]} {at}" if self.lang == "en" else f"{self.t('every')} {day} {at}"
        if dow == "*":
            return f"{'Daily' if self.lang == 'en' else 'Dagelijks'} {at}"
        return f"`{cron}`"

    def open_tasks(self) -> list[dict]:
        tasks = []
        for seat_id, seat in self.d["seats"].items():
            for task in seat["tasks"]:
                if task.get("status", "open") != "done":
                    tasks.append(dict(task, seat=seat_id))
        return sorted(tasks, key=lambda x: str(x.get("due", "9999")))


def page(title: str, description: str, body: str) -> str:
    fm = f"---\ntitle: {json.dumps(title, ensure_ascii=False)}\ndescription: {json.dumps(description, ensure_ascii=False)}\n---\n\n"
    return fm + body.strip() + "\n"


def table(headers: list[str], rows: list[list]) -> str:
    if not rows:
        return ""
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def facts_list(items: list[tuple[str, object]], escape: bool = True) -> str:
    """Label/value pairs as a bulleted list (reads better than a two-column table without headers)."""
    return "\n".join(f"- **{label}:** {(mdx_text(value) if escape else str(value)).strip()}" for label, value in items if value)


def stat_cards(items: list[tuple[int, str]]) -> str:
    cards = "\n".join(f"  <Card title={json.dumps(str(n))} description={json.dumps(label, ensure_ascii=False)} />" for n, label in items)
    return "<Cards>\n" + cards + "\n</Cards>"


def callout(text: str, kind: str = "info") -> str:
    return f'<Callout type="{kind}">\n{text}\n</Callout>'


def mermaid(lines: list[str]) -> str:
    return "```mermaid\n" + "\n".join(lines) + "\n```"


# ---------------------------------------------------------------- pages
def page_overview(s: Site) -> str:
    p, a = s.p, s.d["agreements"]
    notes = []
    if p.get("demo"):
        notes.append(callout(s.t("demo_note"), "warn"))
    facts = facts_list([(s.t("goal"), p.get("goal")), (s.t("phase"), p.get("phase")),
                        (s.t("contract"), p.get("contract")), (s.t("client"), p.get("client"))])
    internal = [x for x in s.d["people"] if not x.get("external")]
    agents = sum(len(seat.get("team", [])) for seat in s.d["seats"].values())
    open_handoffs = [h for h in s.d["handoffs"] if h.get("status") != "done"]
    glance = stat_cards([
        (len(internal), s.t("people_n")), (len(s.positions), s.t("positions_n")), (agents, s.t("agents_n")),
        (len(s.d["decisions"]), s.t("decisions_n")), (len(s.d["meetings"]), s.t("meetings_n")),
        (len(s.open_tasks()), s.t("open_tasks_n")), (len(open_handoffs), s.t("open_handoffs_n")),
    ])
    upcoming = [m for m in a.get("milestones", []) or [] if dt.date.fromisoformat(str(m["date"])) >= s.today][:3]
    milestones = table([s.t("milestone"), s.t("date")], [[mdx_cell(m["name"]), m["date"]] for m in upcoming])
    cards = [f'  <Card title={json.dumps(s.t(k))} href="{s.url(slug)}" />' for k, slug in [
        ("people", "people"), ("ai_teams", "ai-teams"), ("how_we_work", "how-we-work"),
        ("agreements", "agreements"), ("decisions", "decisions"), ("this_week", "this-week")]]
    links = [f'  <Card title={json.dumps(l["title"], ensure_ascii=False)} href={json.dumps(l["url"])} description={json.dumps(l.get("description", ""), ensure_ascii=False)} />'
             for l in p.get("links", []) or []]
    for doc in s.docs.values():
        desc = json.dumps(f"{doc.get('title', '')} · {doc.get('date', '')}", ensure_ascii=False)
        links.append(f'  <Card title={json.dumps(s.t("bep_card"), ensure_ascii=False)} '
                     f'href="{s.files_url}/{Path(doc["file"]).name}" description={desc} />')
    body = "\n\n".join(notes + [
        facts,
        f"## {s.t('at_a_glance')}", glance,
        f"## {s.t('next_milestones')}", milestones or s.t("nothing_yet"),
        "<Cards>\n" + "\n".join(cards) + "\n</Cards>",
        f"## {s.t('links')}", "<Cards>\n" + "\n".join(links) + "\n</Cards>" if links else s.t("nothing_yet"),
        f"_{s.t('generated_note', date=s.today.isoformat())}_",
    ])
    return page(p.get("name", p.get("id", "Project")), mdx_text(p.get("phase", "")), body)


def page_people(s: Site) -> str:
    covers = {c["position"]: c for c in s.active_cover()}
    rows = []
    for pid, pos in s.positions.items():
        holders = []
        for seat in pos.get("held_by", []):
            name = mdx_cell(s.seat_name(seat))
            holders.append(f"{name} ({s.t('lead')})" if pos.get("lead") == seat and len(pos.get("held_by", [])) > 1 else name)
        scope = ", ".join(f"{k}: {v}" for k, v in (pos.get("scope") or {}).items())
        cover = covers.get(pid)
        cover_txt = f"{mdx_cell(s.seat_name(cover['by']))} → {cover['until']}" if cover else "—"
        rows.append([f"`{pid}`", mdx_cell(pos.get("role")), mdx_cell(scope), ", ".join(holders) or "—", cover_txt])
    lines = ["flowchart LR"]
    for pid, pos in s.positions.items():
        lines.append(f'  {node_id("P_", pid)}["{mm(pid)}"]')
        for seat in pos.get("held_by", []):
            lines.append(f'  {node_id("U_", seat)}(["{mm(s.seat_name(seat))}"]) --- {node_id("P_", pid)}')
    for c in s.active_cover():
        label = mm(s.t("covers", pos=c["position"], until=c["until"]))
        lines.append(f'  {node_id("U_", c["by"])} -.->|"{label}"| {node_id("P_", c["position"])}')
    owners = [[mdx_cell(r.replace("-", " ")), f"`{pid}`"] for pid, pos in s.positions.items() for r in pos.get("responsibilities", [])]
    team_rows = [[mdx_cell(x["name"]), mdx_cell(x.get("title")), mdx_cell(x.get("organization"))]
                 for x in s.d["people"] if not x.get("external")]
    ext_rows = [[mdx_cell(x["name"]), mdx_cell(x.get("title")), mdx_cell(x.get("organization"))]
                for x in s.d["people"] if x.get("external")]
    body = "\n\n".join([
        s.t("people_intro"),
        f"## {s.t('positions')}", table([s.t("position"), s.t("role"), s.t("scope"), s.t("held_by"), s.t("cover")], rows),
        mermaid(lines),
        f"## {s.t('who_owns_what')}", table([s.t("responsibility"), s.t("position")], owners),
        f"## {s.t('people')}", table([s.t("name"), s.t("title"), s.t("organization")], team_rows),
        f"## {s.t('external')}", table([s.t("name"), s.t("title"), s.t("organization")], ext_rows) or s.t("nothing_yet"),
    ])
    return page(s.t("people"), s.t("positions") + " · " + s.t("who_owns_what"), body)


def page_ai_teams(s: Site) -> str:
    parts = [s.t("teams_intro")]
    lines = ["flowchart LR"]
    for seat_id, seat in s.d["seats"].items():
        label = f"{s.seat_name(seat_id)} · {', '.join(seat.get('positions', []))}"
        lines.append(f'  subgraph {node_id("S_", seat_id)}["{mm(label)}"]')
        lines.append("    direction TB")
        for member in seat.get("team", []):
            emoji, name, *_ = ROLES.get(member["role"], ("🤖", member["role"], "", {}))
            lines.append(f'    {node_id("S_", seat_id + "_" + member["role"])}["{emoji} {mm(name)}"]')
        lines.append("  end")
    for h in s.d["handoffs"]:
        target = s.positions.get(h.get("to"), {})
        receiver = target.get("lead") or (target.get("held_by") or [None])[0]
        sender = (h.get("from") or {}).get("seat")
        if sender in s.d["seats"] and receiver in s.d["seats"]:
            label = f'{mm(s.t("handoff"))}: {mm(short(h.get("title", "")))}'
            lines.append(f'  {node_id("S_", sender)} -->|"{label}"| {node_id("S_", receiver)}')
    parts.append(mermaid(lines))
    for seat_id, seat in s.d["seats"].items():
        rows = []
        for member in seat.get("team", []):
            emoji, name, tier, what = ROLES.get(member["role"], ("🤖", member["role"], "", {}))
            rows.append([f"{emoji} {mdx_cell(name)}", mdx_cell(what.get(s.lang, "")), mdx_cell(member.get("why")), tier or "—"])
        heading = f"{mdx_text(s.seat_name(seat_id))} · " + ", ".join(f"`{p}`" for p in seat.get("positions", []))
        parts += [f"### {heading}", table([s.t("member"), s.t("what_it_does"), s.t("why"), s.t("model")], rows)]
    parts.append(f"## {s.t('handoffs_title')}")
    hrows = [[h.get("date", ""), mdx_cell(h.get("title")),
              f"{mdx_cell(s.seat_name((h.get('from') or {}).get('seat', '')))} ({mdx_cell(ROLES.get((h.get('from') or {}).get('role'), ('', (h.get('from') or {}).get('role', '')))[1])})",
              f"`{h.get('to')}`", s.t(h.get("status", "open")) if h.get("status") in ("open", "done") else mdx_cell(h.get("status"))]
             for h in s.d["handoffs"]]
    parts.append(table([s.t("date"), s.t("handoff"), s.t("from"), s.t("to"), s.t("status")], hrows) or s.t("no_handoffs"))
    return page(s.t("ai_teams"), s.t("teams_intro").split(".")[0] + ".", "\n\n".join(parts))


def workflow_mermaid(wf: dict) -> str:
    steps = wf.get("steps") or {}
    lines = ["flowchart LR" if len(steps) <= 6 else "flowchart TB"]  # long chains read better top to bottom
    for step_id, step in steps.items():
        nid = node_id("W_", step_id)
        many = " ×n" if step.get("foreach") else ""
        if "agent" in step:
            emoji, name, *_ = ROLES.get(step["agent"], ("🤖", step["agent"], "", {}))
            lines.append(f'  {nid}(["{mm(step_id)}{many}<br/>{emoji} {mm(name)}"])')
        elif "gate" in step:
            lines.append(f'  {nid}{{"✋ {mm(step_id)}"}}')
        elif "workflow" in step:
            lines.append(f'  {nid}[["{mm(step_id)}{many}<br/>↪ {mm(step["workflow"])}"]]')
        elif "script" in step:
            lines.append(f'  {nid}["{mm(step_id)}{many}<br/>🧮 script"]')
        else:
            lines.append(f'  {nid}["{mm(step_id)}{many}<br/>🔌 {mm(step.get("tool", ""))}"]')
        for need in step.get("needs", []) or []:
            lines.append(f"  {node_id('W_', need)} --> {nid}")
    return mermaid(lines)


def page_how_we_work(s: Site) -> str:
    p, a = s.p, s.d["agreements"]
    parts = [s.t("flow_intro"), mermaid([
        "flowchart LR",
        f'  U(["{mm(s.t("people"))}"]) --> C["🧭 Coordinator"]',
        '  C --> W["' + mm(s.t("workflows")) + '"]',
        '  W --> T["🔌 ACC · Revit · Civil 3D · files"]',
        '  W --> G{"✋ ' + mm(s.t("approvals")) + '"}',
        '  G --> U',
    ])]
    owners = ", ".join(mdx_text(s.person_name(o)) for o in p.get("rule_owners", []) or []) or "—"
    parts += [f"## {s.t('approvals')}", facts_list([
        (s.t("write_mode"), s.t(f"write_mode_{p.get('write_mode', 'read-only')}")),
        (s.t("rule_owners"), owners),
    ], escape=False)]
    coord = a.get("coordination")
    if coord:
        parts += [f"## {s.t('rhythm')}", f"{mdx_text(coord.get('description'))}\n\n{s.t('source')}: {s.source(coord.get('source'))}"]
    parts.append(f"## {s.t('workflows')}")
    for wf in s.d["workflows"]:
        parts += [f"### {mdx_text(wf.get('id'))}", mdx_text(wf.get("description", "")), workflow_mermaid(wf)]
    rows = [[f"`{x.get('id')}`", s.cron_human(x.get("schedule", "")), f"`{x.get('owner', '—')}`", mdx_cell(x.get("mode"))]
            for x in s.d["automations"]]
    if rows:
        parts += [f"## {s.t('automations')}", table([s.t("automations"), s.t("schedule"), s.t("owner"), s.t("mode")], rows)]
    return page(s.t("how_we_work"), s.t("approvals") + " · " + s.t("workflows") + " · " + s.t("automations"), "\n\n".join(parts))


KNOWN_AGREEMENTS = {"source_documents", "software", "cde", "naming", "coordinates", "exchange", "classification",
                    "coordination", "milestones", "open_questions"}


def page_agreements(s: Site) -> str:
    a = s.d["agreements"]
    parts = [s.t("agreements_intro")]
    if s.docs:
        rows = [[mdx_cell(d.get("title")), d.get("date", ""), f"[{s.t('download')}]({s.files_url}/{Path(d['file']).name})"]
                for d in s.docs.values()]
        parts += [f"## {s.t('documents')}", table([s.t("title"), s.t("date"), ""], rows)]
    if a.get("open_questions"):
        parts.append(callout(f"**{s.t('open_questions')}**\n\n" + "\n".join(f"- {mdx_text(q)}" for q in a["open_questions"]), "warn"))
    if a.get("software"):
        rows = [[mdx_cell(x.get("app")), mdx_cell(x.get("version")), mdx_cell(x.get("used_for")), s.source(x.get("source"))]
                for x in a["software"]]
        parts += [f"## {s.t('software')}", table([s.t("app"), s.t("version"), s.t("used_for"), s.t("source")], rows)]
    simple = [
        ("cde", lambda v: f"**{mdx_text(v.get('platform'))}** · " + " · ".join(mdx_text(x) for x in v.get("statuses", []))),
        ("naming", lambda v: f"`{v.get('files')}`"),
        ("coordinates", lambda v: f"{mdx_text(v.get('system'))} · {mdx_text(v.get('height'))}"),
        ("exchange", lambda v: " · ".join(mdx_text(x) for x in v.get("formats", []))),
        ("classification", lambda v: " · ".join(mdx_text(x) for x in v.get("systems", []))),
    ]
    for key, render in simple:
        if a.get(key):
            parts += [f"## {s.t(key)}", f"{render(a[key])}\n\n{s.t('source')}: {s.source(a[key].get('source'))}"]
    if a.get("milestones"):
        rows = [[mdx_cell(m["name"]), m["date"], s.source(m.get("source"))] for m in a["milestones"]]
        parts += [f"## {s.t('milestones')}", table([s.t("milestone"), s.t("date"), s.t("source")], rows)]
    other = {k: v for k, v in a.items() if k not in KNOWN_AGREEMENTS}
    if other:
        parts += [f"## {s.t('other_agreements')}", "```yaml\n" + yaml.safe_dump(other, allow_unicode=True, sort_keys=False).strip() + "\n```"]
    return page(s.t("agreements"), s.t("agreements_intro").split(".")[0] + ".", "\n\n".join(parts))


def page_decisions(s: Site) -> str:
    parts = []
    for d in s.d["decisions"]:
        meta = [s.t("decision_by", date=d.get("date", ""), by=mdx_text(s.seat_name(d.get("by", ""))))]
        if d.get("supersedes"):
            meta.append(f"{s.t('replaces')}: " + ", ".join(f"`{x}`" for x in d["supersedes"]))
        if d.get("deviates_from"):
            meta.append(f"{s.t('deviates')}: {mdx_text(d['deviates_from'])}")
        if d.get("source"):
            meta.append(f"{s.t('source')}: {mdx_text(d['source'])}")
        parts += [f"## {mdx_text(d.get('title', d.get('id')))}", "_" + " · ".join(meta) + "_", mdx_markdown(d.get("body", ""))]
    return page(s.t("decisions"), f"{len(s.d['decisions'])} {s.t('decisions_n')}", "\n\n".join(parts) or s.t("nothing_yet"))


def meeting_pages(s: Site) -> dict[str, str]:
    pages = {}
    rows = []
    for m in s.d["meetings"]:
        title = f"{m.get('title', m['slug'])} · {m.get('date', '')}"
        rows.append([m.get("date", ""), f"[{mdx_cell(m.get('title', m['slug']))}]({s.url('meetings/' + m['slug'])})",
                     mdx_cell(s.seat_name(m.get("uploader", "")))])
        minutes = re.sub(r"^# .*\n+", "", m["minutes"], count=1)
        participants = ", ".join(mdx_text(s.person_name(x)) for x in m.get("participants", []))
        header = f"_{s.t('uploaded_by', by=mdx_text(s.seat_name(m.get('uploader', ''))))} · {s.t('participants')}: {participants}_"
        pages[f"meetings/{m['slug']}.mdx"] = page(title, mdx_text(m.get("type", "")), header + "\n\n" + mdx_markdown(minutes))
    index = s.t("meetings_intro") + "\n\n" + (table([s.t("date"), s.t("meetings"), s.t("owner")], rows) or s.t("nothing_yet"))
    pages["meetings/index.mdx"] = page(s.t("meetings"), s.t("meetings_intro").split(".")[0] + ".", index)
    pages["meetings/meta.json"] = json.dumps({"title": s.t("meetings"), "pages": ["index", *[m["slug"] for m in s.d["meetings"]]]}, indent=2, ensure_ascii=False)
    return pages


def page_this_week(s: Site) -> str:
    since = s.today - dt.timedelta(days=6)
    parts = [f"## {s.t('journal')}"]
    entries = []
    for seat_id, seat in s.d["seats"].items():
        for j in seat["journal"]:
            day = dt.date.fromisoformat(str(j.get("date")))
            if since <= day <= s.today:
                text = s.t("private_session") if j.get("private") else mdx_markdown(j["body"])
                entries.append((day, seat_id, text))
    for day, seat_id, text in sorted(entries, key=lambda e: (e[0], e[1]), reverse=True):
        parts += [f"**{mdx_text(s.seat_name(seat_id))}** · {day.isoformat()}", text]
    if not entries:
        parts.append(s.t("nothing_yet"))
    horizon = s.today + dt.timedelta(days=14)
    due = [[mdx_cell(t.get("title")), mdx_cell(s.seat_name(t["seat"])), f"`{t.get('position', '—')}`", t.get("due", "—")]
           for t in s.open_tasks() if t.get("due") and dt.date.fromisoformat(str(t["due"])) <= horizon]
    parts += [f"## {s.t('due_soon')}", table([s.t("task"), s.t("name"), s.t("position"), s.t("due")], due) or s.t("nothing_yet")]
    recent = [[d.get("date", ""), mdx_cell(d.get("title"))] for d in s.d["decisions"]
              if dt.date.fromisoformat(str(d.get("date"))) >= s.today - dt.timedelta(days=14)]
    parts += [f"## {s.t('recent_decisions')}", table([s.t("date"), s.t("decisions")], recent) or s.t("nothing_yet")]
    return page(s.t("this_week"), f"{since.isoformat()} – {s.today.isoformat()}", "\n\n".join(parts))


# ---------------------------------------------------------------- write
def generate(project_root: Path, out_dir: Path, public_dir: Path | None = None, files_url: str | None = None,
             base_url: str = "/docs", today: dt.date | None = None) -> list[Path]:
    data = load_project(project_root)
    pid = data["project"].get("id", project_root.name)
    site = Site(data, base_url, files_url or f"/project-files/{pid}", today or dt.date.today())
    pages = {
        "index.mdx": page_overview(site),
        "people.mdx": page_people(site),
        "ai-teams.mdx": page_ai_teams(site),
        "how-we-work.mdx": page_how_we_work(site),
        "agreements.mdx": page_agreements(site),
        "decisions.mdx": page_decisions(site),
        "this-week.mdx": page_this_week(site),
        **meeting_pages(site),
    }
    title = data["project"].get("name", pid) + (" (demo)" if data["project"].get("demo") else "")
    pages["meta.json"] = json.dumps({"title": title, "pages": ["index", "people", "ai-teams", "how-we-work",
                                                              "agreements", "decisions", "meetings", "this-week"]},
                                    indent=2, ensure_ascii=False)
    if out_dir.exists():
        shutil.rmtree(out_dir)
    written = []
    for rel, content in pages.items():
        path = out_dir / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    if public_dir is not None:
        target = public_dir
        if target.exists():
            shutil.rmtree(target)
        target.mkdir(parents=True)
        for doc in site.docs.values():
            src = project_root / ".bimai" / doc["file"]
            if src.exists():
                shutil.copy2(src, target / src.name)
                written.append(target / src.name)
    return written


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("project_root", type=Path)
    ap.add_argument("content_out_dir", type=Path)
    ap.add_argument("--public-dir", type=Path)
    ap.add_argument("--files-url")
    ap.add_argument("--base-url", default="/docs")
    ap.add_argument("--today", type=dt.date.fromisoformat)
    args = ap.parse_args(argv[1:])
    try:
        written = generate(args.project_root, args.content_out_dir, args.public_dir, args.files_url, args.base_url, args.today)
    except FileNotFoundError as exc:
        print(json.dumps({"ok": False, "error": "invalid_input", "message": str(exc)}))
        return 1
    print(json.dumps({"ok": True, "files": [str(p) for p in written]}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
